name: Engine
version: 1.0
main: io.github.itkova.Main
api-version: 1.18
author: team-plus
description: Api for Plus Team
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.10
commands:
  mention:
    description: 맨션 커맨드입니다
    aliases: [맨션, ㅁㅅ]
  eg:
    description: 엔진서버 컴앤드입니다
    aliases: [engine, 엔진, engineserver]